#!/bin/bash

PS3="Choose commit prefix : "
options=("[ADD]" "[REM]" "[FIX]" "[CODING-STYLE]")
select commitPrefix in "${options[@]}"; do
    case $commitPrefix in
        "[ADD]" | "[REM]" | "[FIX]" | "[CODING-STYLE]")
            break
            ;;
        *)
            echo "Invalid choice. Please select a valid option."
            ;;
    esac
done

read -p "Enter your commit message: " commitMessage

git commit -m "$commitPrefix $commitMessage"

read -p "Do you want to push changes to the remote repository? (y/n): " pushChoice
if [ "$pushChoice" = "y" ]; then
    git push
else
    echo "Changes are staged, but not pushed."
fi
