#!/bin/bash

cp ~/.emacs.default/init.el ~/Emacs-config/.emacs.default/
cp ~/.emacs.tiny/init.el ~/Emacs-config/.emacs.tiny/

cp ~/.emacs.default/custom/* ~/Emacs-config/.emacs.default/custom/
cp ~/.emacs.tiny/custom/* ~/Emacs-config/.emacs.tiny/custom/

cp ~/.emacs.default/epitech/* ~/Emacs-config/.emacs.default/epitech/
cp ~/.emacs.tiny/epitech/* ~/Emacs-config/.emacs.tiny/epitech/

cp ~/.emacs.default/languages/* ~/Emacs-config/.emacs.default/languages/

cd ~/Emacs-config/
mr_clean
